### ISSUE TITLE
QR code looks dodgy

### ISSUE THREAD

**Issue by tyeth** [syncfusion/blazor-samples#108]
Think it's anti-aliasing or something, but the QR code in the local sample (downloaded today) looks weird, there are extra lines/pixels at different zoom levels.
![medium](https://user-images.githubusercontent.com/6692083/93929440-c46e7280-fd13-11ea-8705-ade1164601d3.png)
![small](https://user-images.githubusercontent.com/6692083/93929444-c5070900-fd13-11ea-8cf9-886bb0abdafe.png)
![syncfusionlarge](https://user-images.githubusercontent.com/6692083/93929446-c5070900-fd13-11ea-9c3d-af2dd2e98e63.png)

Windows 10 enterprise insider preview build 20175, chrome latest Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by KameshRajandran** [comment]
Hi Tyeth Gundry,  
  
Reported Issue :  [CrispEdges support for QRcode and DataMatrix](https://www.syncfusion.com/feedback/18216/crispedges-support-for-qrcode-and-datamatrix)
    
We can reproduce the issue and confirmed this as a defect. We have logged a defect report for this issue. We will fix this issue and provide the patch on October 13th 2020, weekly patch release.  
 
Feedback Link:  
  
Regards,  
Kamesh R.

**Comment by KameshRajandran** [comment]
H Tyeth Gundryi,


We have fixed the reported issue and we are glad to announce that our Essential Studio 2020 Volume 3 release v18.3.0.35 is rolled out and is available for download under the following link.


https://www.syncfusion.com/forums/158306/essential-studio-2020-volume-3-release-v18-3-0-35-is-available-for-download


We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Also you can check the UI with below sample link

https://blazor.syncfusion.com/demos/barcodes/qr-code?theme=bootstrap4 

Regards,          

Kamesh R.

**Comment by tyeth** [comment]
Looks great, thanks Kamesh!
