### ISSUE TITLE
Listbox demo - horizontal listbox

### ISSUE THREAD

**Issue by VR-Architect** [syncfusion/blazor-samples#109]
Add this to the demo for others.

https://www.syncfusion.com/feedback/17895/blazor-listbox-horizontal-setting

**Comment by Satheeskumar-1989** [comment]
Hi VR Architect,

Thanks for your suggestion and we will consider this in our knowledge base.

Regards,
Satheeskumar S

**Comment by Satheeskumar-1989** [comment]
Hi VR Architect,

We have published this knowledge base.

https://www.syncfusion.com/kb/13015/how-to-set-the-blazor-listbox-items-as-horizontal-list

Regards,
Satheeskumar S
