### ISSUE TITLE
Responsive data grid

### ISSUE THREAD

**Issue by nssidhu** [syncfusion/blazor-samples#111]
Is it possible to have datagrid convert to card when on mobile device ?
Currently we have to do horizontal scrolling and only few columns are visible on mobile device

**Comment by JawaharJeeva** [comment]
Hi Nssidhu,

We are quite unclear about your exact requirement about converting Datagrid to card. Did you mean, you want the grid as like in the below link?

https://help.syncfusion.com/aspnet-core/grid/responsive#mobile-layout 

If not please share any screenshot or any other information which will be helpful for us to validate and provide you with a solution as early as possible.

**Comment by nssidhu** [comment]
Yes. But in Blazor Webassembly library.
============================================================================================================================================================
    On Tuesday, 6 October, 2020, 08:42:47 am GMT-5, JawaharJeeva <notifications@github.com> wrote:  
 
 


Hi Nssidhu,

We are quite unclear about your exact requirement about converting Datagrid to card. Did you mean, you want the grid as like in the below link?

https://help.syncfusion.com/aspnet-core/grid/responsive#mobile-layout

If not please share any screenshot or any other information which will be helpful for us to validate and provide you with a solution as early as possible.

**Comment by JawaharJeeva** [comment]
Hi Nssidhu,

Currently, we don’t have support for “**Adaptive mobile mode Responsive support**” for Blazor Grid. But we have already considered this requirement as a feature and added to our feature request list. At the planning stage for every release cycle, we review all open features and identify features for implementation based on specific parameters including product vision, technological feasibility, and customer interest. This feature will be included in any of our upcoming releases. 
 
You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through this link.  
Feedback Link : https://www.syncfusion.com/feedback/12486/responsive-support-adaptive-mobile-mode-for-blazor-grid

**Comment by rajendranr-5483** [comment]
@nssidhu ,

The requested feature was implemented and included with 2021 Volume 3 release. 

Find a LIVE demo - https://blazor.syncfusion.com/demos/datagrid/adaptive-rendering?theme=bootstrap5
