### ISSUE TITLE
update to net 5

### ISSUE THREAD

**Issue by ghd258** [syncfusion/blazor-samples#117]
update to net 5

**Comment by Saranya13** [comment]
Hi @ghd258 ,

Greetings from Syncfusion Support.

We will upgrade our Syncfusion Blazor Samples with dotnet 5 and it will be published in GitHub on Volume 1, 2021 main release.

Please let us know if you have any concerns.

Regards,
Saranya M

**Comment by ghd258** [comment]
upgrade our Syncfusion Blazor samples to dot Net 5

**Comment by kmuthukumar23** [comment]
Hi @ghd258,

Sorry for the delay.

We have updated our Blazor demos to .NET 5.0. 

Regards,
Muthukumar K
