### ISSUE TITLE
Gantt Chart not loading

### ISSUE THREAD

**Issue by DanielEggers** [syncfusion/blazor-samples#124]
The page is loading but the Gantt Chart doesn't show up and the navigation isn't working.
Tested in Edge in Chrome on different machines.
The same behavior is shown on the hosted demo page:
https://blazor.syncfusion.com/demos/gantt-chart/resource-allocation?theme=bootstrap4

**Comment by MonishaSivanthilingam** [comment]
Hi DanielEggers,

Greetings from Syncfusion support.

We were not able to replicate the issue you reported in normal cases. The sample loaded properly and we were also able to navigate between the demo and source tabs without any issues. However, we were able to replicate the issue only when we applied localization to the samples. Can you confirm whether you faced this issue when you applied localization in your sample? Meanwhile, we will also check on this issue and provide you with further details within one business day(July 6, 2021).

We appreciate your patience until then.

Regards,
Monisha.

**Comment by DanielEggers** [comment]
Hi Monisha,

you are right, my Windows 10 language settings are German. So if I disable "new CultureInfo("de")" in "public void ConfigureServices(IServiceCollection services)" in Startup.cs the Gantt Chart loads fine.
In your public hosted sample https://blazor.syncfusion.com/demos/gantt-chart/default-functionalities the localization is enabled and therefore I can't see the Gantt Chart.

Regards
Daniel

**Comment by MonishaSivanthilingam** [comment]
Hi DanielEggers,

Thank you for your clarification.

We have considered the issue you reported as a bug and have logged a bug report for it. You can track its status from the below feedback link.

**Feedback:** https://www.syncfusion.com/feedback/26766/issue-with-loading-gantt-when-localization-is-used

The fix will be provided in the patch release scheduled for July 21, 2021.

We appreciate your patience until then.

Regards,
Monisha.

**Comment by MonishaSivanthilingam** [comment]
Hi DanielEggers,

Thank you for your patience.

The reported issue “[Issue with loading Gantt when localization is used](https://www.syncfusion.com/feedback/26766/issue-with-loading-gantt-when-localization-is-used)” has been fixed in version v19.2.47. Please find the release notes from the below link.

**Release Notes:** https://blazor.syncfusion.com/documentation/release-notes/19.2.47/?type=all#gantt-chart

Please contact us if you require any further assistance.

Regards,
Monisha.

**Comment by DanielEggers** [comment]
Thanks Monisha. After upgrading this solution to 19.2.0.51 it works as expected. Your demo sites is still running on the old version.
