### ISSUE TITLE
VSCode Syncfusion Blazor Extension is stuck on installation

### ISSUE THREAD

**Issue by zawhtut** [syncfusion/blazor-samples#128]
The Blazor extension (maybe other Syncfusion extensions as well) couldn't be installed. 
It is stuck at installation.

We can't necessarily reproduce this in VScode UI app. 
But this is shown when we use `code --install-extension` in the terminal.

Visual Studio Code (Version: 1.59.0)
Here are the output in terminal.
```
code --install-extension SyncfusionInc.Blazor-VSCode-Extensions
Installing extensions...
Installing extension 'syncfusioninc.blazor-vscode-extensions'...
(node:86858) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. 
Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
```

**Comment by rqx110** [comment]
face the same problem!

**Comment by kalirajanganeshan** [comment]
We have resolved the reported issue. Could you please install Blazor VS Code Extensions through VS Code UI or terminal by using following comment?

Terminal command:  code --install-extension SyncfusionInc.Blazor-VSCode-Extensions

**Comment by rqx110** [comment]
yes, v19.2.56 has resolved this issue.

**Comment by rajendranr-5483** [comment]
@rqx110 , We are closing this thread now.
