### ISSUE TITLE
RESX and bad side effects on FileUpload control (events loss)

### ISSUE THREAD

**Issue by LyttleG** [syncfusion/blazor-samples#132]
Hi,

Take Resources.en-US.resx and Resources.fr.resx using SfFileManager component then add FileManagerAjaxSettings for Download and Upload then the UI will present fine 'Upload' and 'Download' buttons and they work fine, BUT if you change the culture UI from your browser then switch to French (fr) then the UI refreshes and Upload (aka Télécharger in french, which is wrong, the real translation is Téléverser) button disapeared, then the Download (Télécharger in french, the right translation), then the button is visible but does nothing, click goes to nothing!

Then if you open the RESX file and if you replace 'Télécharger' with 'Upload' and the other 'Télécharger' with Download, then both buttons appears and they work as expected!

I only have tested using FileManager, but I suppose there might be other subtle bugs that only happen...

**Comment by Indhumathy-Loganathan** [comment]
Hi @LyttleG,

We considered to correct this in our online GitHub location. It will be refreshed in our upcoming volume releases.

As of now, we suggest you to manually change the translation of Upload operation as **Téléverser** in the resource file. You can find the Blazor sample with modified resource file in below link.

https://www.syncfusion.com/downloads/support/directtrac/344770/ze/Demo-420427275

**Comment by thirukumaran-murugan** [comment]
Hi @LyttleG ,

We have updated the translation of Upload operation as Téléverser in the resource file and refreshed in the GitHub location. Please make use of the latest Blazor samples to overcome the issue.

https://github.com/syncfusion/blazor-samples/

Regards,
Thirukumaran M.
