### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by LacLuc** [syncfusion/blazor-samples#133]
- Issue Type: `Bug`
- Extension Name: `Blazor-VSCode-Extensions`
- Extension Version: `19.3.53`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.62.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by syncsiva** [comment]
Duplicate of https://github.com/syncfusion/blazor-samples/issues/125
