### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Milesgo** [syncfusion/blazor-samples#139]
- Issue Type: `Performance`
- Extension Name: `Blazor-VSCode-Extensions`
- Extension Version: `19.4.48`
- OS Version: `Darwin arm64 21.3.0`
- VS Code version: `1.65.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/l7/tjqs57c1787dmtfrdtc3ck2w0000gn/T/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by GanesanRengasamy** [comment]
Hi @Milesgo,

Thanks for contacting Syncfusion. 

We are preparing the same machine configuration which is you have with the **OS version: Darwin arm64 21.3.0 and VS Code version: 1.65.2**. We will check the reported problem in this machine configuration and update the details further **on or before 21st March 2022**. We appreciate your patience until then.

Regards,
Ganesan Rengasamy.

**Comment by AbishakeD** [comment]
Hi Milesgo,

We checked this issue in machine configure with OS version: Darwin arm64 21.3.0 and VS Code version: 1.65.2 from our side. We didn’t face any performance issue for our Blazor VS Code extension in that machine.

Could you please share the SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt file which is generated in your machine from below location to check further about this issue?

file:///var/folders/l7/tjqs57c1787dmtfrdtc3ck2w0000gn/T/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt

Regards,
Abishake Dakshinamoorthy

**Comment by AbishakeD** [comment]
Hi @Milesgo,

Please provide the details requested in the last update to check this issue further.

Thanks,
Abishake

**Comment by syncsiva** [comment]
@Milesgo  This issue has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
