### ISSUE TITLE
SfProgressButton bug?

### ISSUE THREAD

**Issue by cld0815** [syncfusion/blazor-samples#140]
Hi~

Theme： bootstrap5
```
<SfProgressButton CssClass="e-success e-small e-round">
    <ProgressButtonSpinSettings Position="SpinPosition.Center"></ProgressButtonSpinSettings>
    <ProgressButtonAnimationSettings Effect="Syncfusion.Blazor.SplitButtons.AnimationEffect.ZoomOut"></ProgressButtonAnimationSettings>
</SfProgressButton>
```

The Spin sometimes not in the middle
![1](https://user-images.githubusercontent.com/30192550/159398473-25327d79-aac3-4bde-9c87-480ccbeeaeb8.png)
![2](https://user-images.githubusercontent.com/30192550/159398478-79431e08-51f5-4d4a-a894-e6925cb868fc.png)

**Comment by syncsiva** [comment]
This issue has not had any activity for 1 week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
