### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by douglassimaodev** [syncfusion/blazor-samples#141]
Where are the codes?

I cant use the samples from website
https://blazor.syncfusion.com/documentation/datagrid/getting-started

cant find 
`<link   href="_content/Syncfusion.Blazor.Themes/bootstrap5.css" rel="stylesheet" />`

also table does not display, is blazor components read to be used?

I am using blazor webassembly 6.0

**Comment by syncsiva** [comment]
@douglassimaodev 
Can you please ensure [Syncfusion.Blazor.Themes]([Syncfusion.Blazor.Themes](https://www.nuget.org/packages/Syncfusion.Blazor.Themes/) NuGet references in your project.

If you have installed already and still style not applied. Can you please ensure static web assets usages enabled in project.
https://blazor.syncfusion.com/documentation/appearance/themes#enable-static-web-assets-usage

**Comment by syncsiva** [comment]
This issue has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
