### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by danielbichuetti** [syncfusion/blazor-samples#142]
- Issue Type: `Performance`
- Extension Name: `Blazor-VSCode-Extensions`
- Extension Version: `20.1.55`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.68.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/danie/AppData/Local/Temp/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by kalirajanganeshan** [comment]
Hi @danielbichuetti ,

We checked this issue in Windows machine configure with your VS Code version: 1.68.0 from our side. We didn’t face any performance issue for our Blazor VS Code extension in that machine.

Could you please share the SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt file which is generated in your machine from below location to check further about this issue?

file:///c%3A/Users/danie/AppData/Local/Temp/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt

Regards,
Kalirajan Ganesan
