### ISSUE TITLE
Can't select .net 6 core version while creating project from 'Syncfusion Blazor Template Studio (vscode)'

### ISSUE THREAD

**Issue by rqx110** [syncfusion/blazor-samples#143]
![image](https://user-images.githubusercontent.com/1829209/182542079-70fac8a1-448f-4a10-bb5f-e00323eabfa6.png)

.net sdks on my machine:
![image](https://user-images.githubusercontent.com/1829209/182542443-c5a93456-9350-4757-bf27-e37a312d40b1.png)

**Comment by AbishakeD** [comment]
Hi rqx110,

Thank you for contacting Syncfusion support

We checked this issue from our side. We are able to select a .NET 6.0 version and create an application successfully. 

Could you please share the below details to check further about this issue from our side?
1.	Share the OS Version on your machine
2.	Share the screenshot of VSCode information by going to Help->About in Visual Studio Code.


Please let us know if you have any concerns about this.

Regards,
Abishake Dakshinamoorthy

**Comment by rqx110** [comment]
Version: 1.69.0 (system setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by rqx110** [comment]
And version info of "Syncfusion Blazor Template Studio" extension:

Name: Blazor VSCode Extensions - Syncfusion
Id: SyncfusionInc.Blazor-VSCode-Extensions
Description: Syncfusion Essential Studio for Blazor Visual Studio Code extension includes Blazor project templates, code snippet, conversion, and migration tools.
Version: 20.2.36
Publisher: Syncfusion
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=SyncfusionInc.Blazor-VSCode-Extensions

**Comment by AbishakeD** [comment]
Hi rqx110,

Thank you for sharing details

We checked this issue in given VS Code version and machine combination. But we unable to reproduce this issue. We seem some issue occurred while getting .NET6.0 sdk version from registry editor.

So could you please do the below steps and share the log file to provide the proper solution for this issue from our side?

1. Download this [GetSDKVersionTool.zip](https://github.com/syncfusion/blazor-samples/files/9315702/GetSDKVersionTool.zip) file and extract it.  In extracted location, double click GetSDKVersionTool.exe and share the generated SyncfusionLog.txt file in the same location.
2. Share the log file located in the below locations

    “{UserProfile}\.vscode\extensions\syncfusioninc.blazor-vscode-extensions-20.2.36\logs”
   “{LocalAppdata}\SyncTS\Logs”

Please let us know if you have any concerns about this.

Regards,
Abishake Dakshinamoorthy

**Comment by rqx110** [comment]
syncfusionlog.txt
```
Windows:

Register Entry:

Register Details: HKEY_LOCAL_MACHINE\Software\Wow6432Node\dotnet\Setup\InstalledVersions\x64\sdk

isDotNetCoreSdkInstalled: False



Command Line:

3.1.421 [C:\Program Files\dotnet\sdk]
5.0.411 [C:\Program Files\dotnet\sdk]
6.0.400 [C:\Program Files\dotnet\sdk]


isDotNetCoreSdkInstalled: True
```
[syncfusionts.log](https://github.com/syncfusion/blazor-samples/files/9334400/syncfusionts.log)

**Comment by rqx110** [comment]
it looks like missing .net6 info in registry. I add it manually and it works
