### ISSUE TITLE
Can't create release build due to missing package.json?

### ISSUE THREAD

**Issue by dbruning** [syncfusion/blazor-samples#144]
If I try to build in release mode, I get error:
`  BlazorServerCommon_NET6.csproj(18, 5): [MSB3073] The command "npm install" exited with code -4058.`

It looks like that's because BlazorServerCommon_NET6.csproj has this:

```
<Target Name="ProductionBuild" BeforeTargets="BeforeBuild" Condition="'$(Configuration)'=='Release'">
    <Exec Command="npm install" />
    <Exec Command="npm run minify" />
  </Target>
```

... but the 'npm install' and 'npm run minify' commands would need to reference a package.json file, which isn't in the repo?

More info from the build log:
```
1>ProductionBuild:
         npm install
         npm ERR! code ENOENT
         npm ERR! syscall open
         npm ERR! path C:\code\syncfusion-blazor-samples\Common/package.json
         npm ERR! errno -4058
         npm ERR! enoent ENOENT: no such file or directory, open 'C:\code\syncfusion-blazor-samples\Common\package.json'
         npm ERR! enoent This is related to npm not being able to find a file.
         npm ERR! enoent 
```

**Comment by Lingala-Joshna** [comment]
Hi dbruning,

Sorry for the inconvenience caused.

We have validated the reported issue at our end. We have included the missed files in the repository. Could you please pull the changes and build the solution.

[https://github.com/syncfusion/blazor-samples](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsyncfusion%2Fblazor-samples&data=05%7C01%7Cjoshnalingala.u%40syncfusion.com%7C67be77d08845409e566508da7a7f6172%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637956984828145971%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bXns3JeXqSGwl2YKq5MkR9KviXloO%2F%2BxTgl4ViPZ1Ag%3D&reserved=0)

Please get back to us if you have any queries.

Regards,
Joshna L

**Comment by syncsiva** [comment]
This issue has been resolved. Please feel free to reopen if you have any further queries.
