### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mastaler** [syncfusion/blazor-samples#146]
- Issue Type: `Performance`
- Extension Name: `Blazor-VSCode-Extensions`
- Extension Version: `20.2.43`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/fabio/AppData/Local/Temp/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by AbishakeD** [comment]
Hi @mastaler ,

We checked this issue in a Windows machine configured with your VS Code version: 1.70.1 from our side. We did not face any performance issues for our Blazor VS Code extension in that machine.

Could you please share the below details to check further about this issue?

1. Share the SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt file which is generated in your machine from the below location
        file:///c%3A/Users/fabio/AppData/Local/Temp/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt 

2. Share the video demonstration to replicate the issue.

3. Share the screenshot of the issue in Visual Studio code.

Please let us know if you have any concerns

Regards,
Abishake Dakshinamoorthy

**Comment by syncsiva** [comment]
This issue has been closed due to no response from the original author. Please feel free to reopen, if you have more information that can help us investigate the issue further.
