### ISSUE TITLE
Tailwind CSS Leaves blue block around clicked button 

### ISSUE THREAD

**Issue by thetechyghost** [syncfusion/blazor-samples#149]
When using with Tailwind CSS, buttons seem to have a blue border that does not go away until the button loses focus again. 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/79113008/196332638-a9a14747-e5cb-4902-b2fd-6fa25f93e156.png">

The above screenshot was taken from the Blazor Demo page 
https://blazor.syncfusion.com/demos/buttons/default-functionalities?theme=tailwind and was reproduce din my own code.

**Comment by Yuvan111** [comment]
Hi @thetechyghost ,

**Query:** When using with Tailwind CSS, buttons seem to have a blue border that does not go away until the button loses focus again?

We have checked your reported query and we would like to let you know that, based on the tailwind theme official site we have provided the theme support for our button component, it is behavior of the tailwind button. Kindly refer the below tailwind official pages and get back to us, if you need any further assistance on this.

Tailwind official link: https://tailwindcss.com/

Regards,

YuvanShankar A

**Comment by thetechyghost** [comment]
It is not the behavior of the tailwind button. This is something happening on the component side. Have used Tailwinds before and never came across this. Tailwind is a utility class based system, somewhere you are feeding those classes into the components, but can't find out where, so must be happening on the Blazor component themselves.



-Casper
***@***.******@***.***>

________________________________

**Comment by thetechyghost** [comment]
Also, please check your other demos. Like Blazor Button Split Button Example - Syncfusion Demos<https://blazor.syncfusion.com/demos/buttons/split-button?theme=tailwind> - This does not look right
Blazor Button Split Button Example - Syncfusion Demos<https://blazor.syncfusion.com/demos/buttons/split-button?theme=tailwind>
This example demonstrates the Split Button in Blazor Button Component. Explore here for more details.
blazor.syncfusion.com


-Casper
***@***.******@***.***>
________________________________

**Comment by thetechyghost** [comment]
It's this CSS property causing the issue e-btn:focus

[cid:f22e4a22-c405-4ea2-8097-2a06c4ff431e]



-Casper
***@***.******@***.***>
________________________________

**Comment by Yuvan111** [comment]
In our demo, the Syncfusion buttons are just for showing the button appearance. If we specify a click action (trigger event) for the button, the focus will be automatically removed once we click it. Refer to the below drop-down menu demos.

Demo link:  https://blazor.syncfusion.com/demos/buttons/dropdown-menu?theme=tailwind

And on the tailwind official page, the default button also behaves like that only.

Tailwind page link: https://tailwindui.com/components/application-ui/forms/form-layouts

Note: Click on the "Save" button of the above link.

**Comment by thetechyghost** [comment]
Ok, couple of notes though. 

1. For Tailwind styling to apply to your components, it seems like you must configure tailwind.config.js with the `"important: true` option
2. Also, disable the ring on all components you must use

`:focus:not(:focus-visible) {
    @apply focus:ring-0 focus:ring-offset-0 !important;
}

:focus-visible {
    @apply ring-2 ring-offset-2 !important;
}`

in a custom CSS or similar. 

Not sure if there are going to be any other side effects, but guess I'll find out.

**Comment by Yuvan111** [comment]
Thank you for your suggestion about the button component styling. We have implemented the suggested styles using the standard guidelines provided by Tailwind CSS. We have tested the changes at a sample level and can confirm that they do not have any negative side effects. If you would like to disable the ring on the buttons, as suggested, you can use a custom theme.

**Comment by syncsiva** [comment]
This issue has not had any activity for one week. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
