### ISSUE TITLE
Locale="de-DE" not working

### ISSUE THREAD

**Issue by uwefms** [syncfusion/blazor-samples#15]
I am using schedule with server-side blazor and the provided ScheduleData from the samples with the following version :

`<PackageReference Include="Microsoft.NETCore.Platforms" Version="3.0.0-preview4.19212.13" />
<PackageReference Include="Syncfusion.EJ2.AspNet.Core.RazorComponents" Version="17.1.0.43-beta" />`

using

`<EjsSchedule id="schedule"
			 width="100%"
			 height="650px"
			 selectedDate="new DateTime(2019, 1, 10)"			 
			 EventSettings="@eventSettingsFields"	
			 ActionComplete="@OnComplete"
			 Locale="de-DE"
			 >
</EjsSchedule>`

Locale="en-US" is working but Locale="de-DE" does not load the data.

**Comment by karthigeyan92** [comment]
Dear Customer,  

Greetings from Syncfusion.

Currently no locale support for Syncfusion blazor components.

Regards,
Karthi

**Comment by karthigeyan92** [comment]
Dear Customer,

Greetings from Syncfusion.

Currently no locale support for Syncfusion blazor components. We have already logged feature for locale support and it will included in any one of our upcoming main release.

Regards,
Karthi

**Comment by rajendranr-5483** [comment]
Dear customer, 

We have added localization support to Blazor Schedule component. please find the link for your reference.
https://ej2.syncfusion.com/blazor/documentation/schedule/localization/?no-cache=1

Regards,
Rajendran R.
