### ISSUE TITLE
Error while showing Ticks and Labels sample source

### ISSUE THREAD

**Issue by Dev-Power** [syncfusion/blazor-samples#151]
When I try to show the source on this page https://blazor.syncfusion.com/demos/circular-gauge/ticks-and-labels?theme=bootstrap5

I get an error in the JavaScript console that looks like this:

![Screenshot 2023-01-03 at 15 17 32](https://user-images.githubusercontent.com/91638866/210386293-cb4c3b54-1891-46ef-8b3e-25d9b5217bcd.png)

The demo section works, but this only happens when you switch to the Source section.

Hope this info helps to resolve the issue. If you need more info, please let me know.

Thanks.

**Comment by syncsiva** [comment]
@Dev-Power  Closing for housekeeping purposes. Further, the reported bug can be tracked through below feedback link further,
https://www.syncfusion.com/feedback/40290/source-tab-of-the-ticks-and-labels-sample-throws-exception-in-circular-gauge
