### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by swapnilguptaTW** [syncfusion/blazor-samples#155]
- Issue Type: `Performance`
- Extension Name: `Blazor-VSCode-Extensions`
- Extension Version: `22.2.5`
- OS Version: `Darwin x64 22.6.0`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/f5/gvqsh5r50plbvclf7d49kh340000gn/T/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Kesavaraman123** [comment]
Hi @swapnilguptaTW ,

We checked this issue in a Windows machine configured with your VS Code version: 1.81.1 from our side. We did not face any performance issues for our Blazor VS Code extension in that machine.

Could you please share the below details to check further about this issue?

1. Share the SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt file which is generated in your machine from the below location
file:///c%3A/Users/mortl/AppData/Local/Temp/SyncfusionInc.Blazor-VSCode-Extensions-unresponsive.cpuprofile.txt
2. Share the video demonstration to replicate the issue.
3. Share the screenshot of the issue in Visual Studio code.

Please let us know if you have any concerns

Regards,
V. Kesavaraman

**Comment by gsumankumar** [comment]
This issue has been inactive for over a week, so we are closing it for housekeeping purposes. If you have any additional information to assist us, please reopen the issue. Thank you for your understanding.
