### ISSUE TITLE
Missing documentation on schedule CRUD

### ISSUE THREAD

**Issue by uwefms** [syncfusion/blazor-samples#16]
At the moment there is no documentation on CRUD operations using the schedule component. I wonder which is the best event to get called from the .razor file. I found ActionComplete as a possible way like:

`@page "/"

@using Syncfusion.EJ2.RazorComponents.Schedule

`<EjsSchedule id="schedule"
			 width="100%"
			 height="650px"
			 selectedDate="new DateTime(2019, 1, 10)"			 
			 EventSettings="@eventSettingsFields"	
			 ActionComplete="@OnComplete"			 
			 >
</EjsSchedule>`

@functions{

	EjsSchedule scheduleObj;

	static ScheduleData data = new ScheduleData();

	[Parameter]
	private object ScheduleData { get; set; } = new
	{
		dataSource = data.GetScheduleData()
	};

	private void OnComplete(ActionEventArgs data)
	{
		// check data for db action		
	}

        // renaming some fields
	[Parameter]
	private object eventSettingsFields { get; set; } = new
	{
		dataSource = data.GetScheduleData(),
		fields = new
		{
			subject = new { title = "Titel", name = "Subject" },
			location = new { title = "Ort", name = "Location" },
			description = new { title = "Beschreibung", name = "Description" },
			startTime = new { title = "Start Zeit", name = "StartTime" },
			endTime = new { title = "End Zeit", name = "EndTime" }
		}
	};
}
`
Are there other ways to get to the changed / deleted data ?

**Comment by karthigeyan92** [comment]
Dear Customer,

Greetings from Syncfusion.

Syncfusion uses DataManager to perform CRUD operations and currently there is no DataManager support available in Blazor. We have feature request for the same and will be implemented in any one of our upcoming release.
**Core**: https://ej2.syncfusion.com/aspnetcore/documentation/schedule/data-binding/?no-cache=1#scheduler-crud-actions

Regards,
Karthi

**Comment by rajendranr-5483** [comment]
Hi Uwe Hein,

Now, we have added support for Data manager and CRUD operation in Schedule. Find reference links for more details.

Data manager: https://ej2.syncfusion.com/blazor/documentation/data/getting-started/?no-cache=1
Schedule: https://ej2.syncfusion.com/blazor/documentation/schedule/data-binding/?no-cache=1

Regards,
Rajendran R.
