### ISSUE TITLE
SfDocumentEditorContainer: Loading DOCX is too slow in a Blazor WASM APP

### ISSUE THREAD

**Issue by 1spb-org** [syncfusion/blazor-samples#164]
SfDocumentEditorContainer: 
Loading DOCX is too slow in a Blazor WASM APP - more than 4 seconds for 10 page text document with tables.

**Comment by dhanushsekar123** [comment]
The Document editor is one of the large functionalities covered component as it gives you many functionalities of Microsoft Word application. It has more UI views like text properties pane, header footer properties pane, image properties pane and dialogs.
The dependency components are [Syncfusion.Blazor.Calendars](https://www.nuget.org/packages/Syncfusion.Blazor.Calendars/), [Syncfusion.Blazor.Core](https://www.nuget.org/packages/Syncfusion.Blazor.Core/), [Syncfusion.Blazor.Data](https://www.nuget.org/packages/Syncfusion.Blazor.Data/), [Syncfusion.Blazor.DropDowns](https://www.nuget.org/packages/Syncfusion.Blazor.DropDowns/), [Syncfusion.Blazor.Navigations](https://www.nuget.org/packages/Syncfusion.Blazor.Navigations/), [Syncfusion.WordProcessor.AspNet.Core](https://www.nuget.org/packages/Syncfusion.WordProcessor.AspNet.Core/), [System.Text.Json](https://www.nuget.org/packages/System.Text.Json/). So, it takes some time (less than 6seconds) for initial loading in client browsers to load all the dependency components and it is an expected one.

Could you please share your document? It will be helpful to validate further and provide you the solution at the earliest.

**Comment by kesavan-duraisamy** [comment]
@1spb-org: This issue has been inactive for an extended period. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
