### ISSUE TITLE
SfDocumentEditorContainer, DOCX File: 90-deg rotated text is failed to render correctly in a Blazor WASM APP

### ISSUE THREAD

**Issue by 1spb-org** [syncfusion/blazor-samples#165]
SfDocumentEditorContainer, DOCX File: 90-degree rotated text is failed to render correctly in a Blazor WASM APP.
It appears as if no rotation was applied.

**Comment by dhanushsekar123** [comment]
Currently, document editor doesn’t provide support for shape rotation.



We have already logged this as feature request. We don’t have any immediate plans to implement this feature now.
 We will let you know when this feature is implemented.            

You can track the status of feature from the below link:            

[Support for rotating image & shape in JavaScript | Feedback Portal (syncfusion.com)](https://www.syncfusion.com/feedback/7700/support-for-rotating-image-shape)

**Comment by kesavan-duraisamy** [comment]
@1spb-org : This issue has been inactive for an extended period. Closing for housekeeping purposes. Please feel free to reopen it if you have more information that can help us investigate the issue further.
