### ISSUE TITLE
ConnectionChange provides JObjects only

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#26]
The Diagram Action "ConnectionChange" provides JObjects only. I'm not able to cast the inner connector to a DiagramConnector for that reason.

https://help.syncfusion.com/cr/aspnetcore-blazor/Syncfusion.EJ2.RazorComponents~Syncfusion.EJ2.RazorComponents.Diagrams.EjsDiagram~ConnectionChange.html

**Comment by RamyaThiru** [comment]
Hi,

Currently, we don’t have support to get an event argument with specific type. We have already logged this requirement as feature report, and it will be available in our Volume 2 Beta release which is tentatively scheduled on end of June 2019.

Now, you can track the status of your request through below link.

Link: https://www.syncfusion.com/feedback/6956/support-to-use-the-event-arguments-with-specific-type-blazor-type

We will get back to you once our Volume 2 beta is released.


Regards,
Ramya T

**Comment by endeffects** [comment]
Oh ok, thank you.

**Comment by Sridhar-Narasimhan** [comment]
We have fixed this issue in the below feedback link and we are closing this item.

https://www.syncfusion.com/feedback/6956/support-to-use-the-event-arguments-with-specific-type-blazor-type
