### ISSUE TITLE
Validating Connectors / Nodes

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#28]
I was looking to your documentation, blog and your support forum, but i found no suitable sample on how to validate the connections between nodes. I tried to use ports and the ConnectionChange action but i failed to get it working.

I have the requirement to provide different kind of nodes where each node type has it's own set of rules which defines which other node type is allowed to connect to.

Sample:

NodeA - allows no inbound connection, but allows to connect to NodeB and Node C
NodeB - allows inbound connections from NodeA and allows to connect to Node D
NodeC - allows inbound connections from NodeA and allow outbound connections to NodeD
NodeD - allows inbound connections from NodeB and NodeC only

**Comment by RamyaThiru** [comment]
Hi @endeffects,

Currently, we don’t have support to cancel the runtime changes/decision with Events. We have considered this as a feature request. We have logged the feature report for this. We will implement and include this support in our Volume 3 release on October 2019. We will get back to you once our Volume 3 is released.

Now, you can track the status of your request through the below feedback link.

Link: https://www.syncfusion.com/feedback/7005/support-to-cancel-the-runtime-changes-with-connectionchange-event

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you, so it is also not possible to do this with ports at the moment, right?

**Comment by RamyaThiru** [comment]
Hi @endeffects,

The connection changes (source and target end) at runtime will be notified through the ConnectionChange event. if we try to make connection with invalid port or node, currently we don’t have support to cancel this action with the event. We will consider the port and node related runtime interaction scenarios while implementing “Cancel the runtime changes/decision with events” support. 

As already informed, We will implement and include this support in our Volume 3 release on October 2019. We will get back to you once our Volume 3 is released.

Regards,
Ramya T

**Comment by Sridhar-Narasimhan** [comment]
We have fixed this issue in the below feedback link and we are closing this item.

https://www.syncfusion.com/feedback/7005/call-back-support-for-the-runtime-changes-notification-events
