### ISSUE TITLE
Scroll on Mouse-Down 

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#36]
Instead of activating the multi selector tool i'd like to scroll the diagram when i hold the mouse button. Similar to google maps:

https://www.google.de/maps/@56.7510641,15.8016268,7.99z

**Comment by RamyaThiru** [comment]
Hi,

We have support to pan the diagram using “Tool” property of the Diagram. We have provided code example for this. Please refer to the code example as below.

Code example:
 ` <EjsDiagram ref="diagram" id="diagram" Width="1000" Height="1000" Tool="DiagramTools.ZoomPan">
</EjsDiagram>`

Defect information:
We are facing exception when using “Tool” property. We have already logged this issue. The fix will be available in our Volume 2 main release on July 2019. 

This issue can be tracked through the below feedback link.

Link: https://www.syncfusion.com/feedback/7115/diagram-throws-index-out-of-bound-exception-when-using-constraints-and-tools

We will get back to you once our Volume 2 main release is rolled out.

Regards,
Ramya T

**Comment by endeffects** [comment]
Thanks you, i already tried this, but it had no effect. 
I'm still getting the multi selection tool.
Than i'm going to wait for the update. :)

**Comment by endeffects** [comment]
With the latest update the ZomPan works as expected. But it is allways active and brakes the SingleSelect still if the ZoomPan Tool is not asigned.

**Comment by RamyaThiru** [comment]
Hi

From our 17.2.30- beta version, we can render non-interactive diagram or static diagram with basic interactions such as zooming and panning alone. The selection and symbol palette will not available. 

Currently, we are working on to provide better runtime interactions support in diagram based on Blazor architecture. We will include the interactions support in diagram one by one soon.

Can you provide your requirements in detail? It will help us to prioritize the work items and serve you better.

Please find the release note for this change.
Link: https://ej2.syncfusion.com/aspnet-core-blazor/documentation/release-notes/index/#diagram
You can track the status of interaction support through below feedback link.
Link: https://www.syncfusion.com/feedback/7441/provide-interaction-support-for-diagram
Regards,
Ramya T

**Comment by endeffects** [comment]
My basic requirements are: 

- I need an interactive diagram with 100% width and hight 
- I need a palette where i can drop nodes and connectors from
- The Palette needs to be updateable / resizeable at runtime
- I also need to validate the connectors for the source and target nodes
- I need the possibility to zoom in and out by custom controls
- I need an overview where i can jump to every point on the diagram (without zooming)
- I need to add custom tools / commands to specific node types (i.e.: copy, delete)
- I need to adjust the scroll speed of the diagram when i move a node to the edges of a diagram
- I need to update the diagram at runtime (data binding) to support multiple users on the same diagram

**Comment by RamyaThiru** [comment]
Hi ,

Thanks for sharing your diagram requirements.

We have validated the provided requirements, and these are the basic diagram interaction features. Currently, we are working on to provide better runtime interactions support in diagram based on Blazor architecture in high priority. We will include the interactions support in diagram one by one soon.  We will get back to you once the interaction support is provided in diagram.

Link: https://www.syncfusion.com/feedback/7441/provide-interaction-support-for-diagram 

Regards, 
Ramya T

**Comment by Sridhar-Narasimhan** [comment]
We have provided all interaction support to blazor diagram component,  So we can close this report. Please find the following link

**Documentation link:**https://ej2.syncfusion.com/documentation/diagram/getting-started/?no-cache=1
**Sample Browser Link:** https://ej2.syncfusion.com/demos/#/material/diagram/default-functionalities.html
