### ISSUE TITLE
Diagram ZoomOut is broken

### ISSUE THREAD

**Issue by endeffects** [syncfusion/blazor-samples#46]
With the latest version the diagram zoom-out is broken,
both zoom in and out are zooming in.

```
        public async Task ZoomIn()
        {
            base.ZoomTo(new ZoomOptions { Type = ZoomTypes.ZoomIn, ZoomFactor = 0.2 });
            await Task.CompletedTask;
        }

        // Does not work anymore.
        public async Task ZoomOut()
        {  
            base.ZoomTo(new ZoomOptions { Type = ZoomTypes.ZoomOut, ZoomFactor = 0.2 }); 
            await Task.CompletedTask;
        }
```

**Comment by RamyaThiru** [comment]
Hi,

We can reproduce the reported issue with zoom out action. We have logged it into our backlog and will include the fix in our NuGet release on or before July 15th, 2019. 

You can track this bug through the below feedback link.

Link: https://www.syncfusion.com/feedback/7274/zoomout-action-works-like-zoomin-operation-in-blazor

As a workaround, you can use the below code snippet.

Code snippet:
```
object options = new { Type = "ZoomOut", ZoomFactor = 0.2 };
this.diagram.ZoomTo(options);
this.diagram.DataBind();
```


Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/zoomOutdiagramsample-1879634898

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you :)

**Comment by RamyaThiru** [comment]
Hi,

Reported issue : zoomout action works like zoomin operation in Blazor

We are glad to announce that our weekly package is released successfully. We have included the fix for the reported issue with this weekly release . Please upgrade to your latest version(17.2.0.34-beta ).

Link: https://www.nuget.org/packages/Syncfusion.EJ2.Blazor/17.2.0.34-beta

Regards,
Ramya T

**Comment by Sridhar-Narasimhan** [comment]
We have fixed this issue in the below feedback link and we are closing this item 

Feedback Link:  https://www.syncfusion.com/feedback/7274/zoomout-action-works-like-zoomin-operation-in-blazor
