### ISSUE TITLE
Individual control nuget packages

### ISSUE THREAD

**Issue by nm-a** [syncfusion/blazor-samples#67]
Dear team,
Application size is one of the major issue that we have with Blazor Client Side today. 

If you can allow users to include independent nuget packages of controls like Syncfusion Xamarin Forms, it will be helpful users to address application size upto some extent.

I hope CRG (https://crg.syncfusion.com/) works here as well.

thank you

**Comment by ajithr** [comment]
@nm-a  Thanks for your feedback and sorry for the delayed response. We have already logged a feature request for this and it can be tracked in the below link.

https://www.syncfusion.com/feedback/9160/individual-assemblies-for-all-syncfusion-blazor-components

We will implement and include this in our upcoming Essential Studio volume release.

**Comment by ajithr** [comment]
@nm-a Thanks for your patience. We are happy to let you know that our Essential Studio Volume 4, 2020 (v18.4.0.30) is released now and the feature "Individual NuGet packages for Syncfusion Blazor UI components" also included in this release. Please refer to the below UG documentation for further details.

https://blazor.syncfusion.com/documentation/nuget-packages/
