### ISSUE TITLE
Load more than one language

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#76]
When I load more than one language I got the following error:

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/3521524/69162384-32be2500-0ab2-11ea-9648-74c30555d4dd.png">

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/3521524/69162400-3782d900-0ab2-11ea-90e8-7705fb3f4365.png">

1. I'm using Blazor wasm
2. The languages I'm loading are English and Spanish

**Comment by Saranya13** [comment]
Hi @OscarCanek ,

Greetings from Syncfusion.

We have checked your reported issue and we need further details. Can you please share the below details for us? It will be helpful for us to focus on a specific area and assist you at the earliest.

1. Share your requirements?
2. Can you please tell us, what is the purpose of referring the two locale in your application?
3. Share the sample with the replication procedure?
4. How you have defined your localization?

Regards,
Saranya M

**Comment by OscarCanek** [comment]
1. I want the user can change the language of the app by selecting a language on a drop down list
2. Allow the user to change the language of the components switching between Spanish and English
3 and 4

```
        if (firstRender)
        {
            var locale = await Http.GetJsonAsync<object>($"ej2-locale/src/es-GT.json");
            var locale2 = await Http.GetJsonAsync<object>($"ej2-locale/src/en-US.json");
            this.JsRuntime.Ejs().LoadLocaleData(locale2).LoadLocaleData(locale);
        }

        if (currentLang.Equals("En"))
        {
            Console.WriteLine("English");
            this.JsRuntime.Ejs().SetCulture("en-US");
        }
        else
        {
            Console.WriteLine("Spanish");
            this.JsRuntime.Ejs().SetCulture("es");
        }
```

> If I set only one at never switch between them works perfect

**Comment by Saranya13** [comment]
Hi @OscarCanek ,

We have created the customer requirements with WebAssembly application. Please find the below code snippet to load more than one language to our components.

`[Inject]
    protected IJSRuntime JsRuntime { get; set; }
private async Task onChange(Syncfusion.EJ2.Blazor.DropDowns.ChangeEventArgs<string> args)
    {
       DropVal = args.Value;
        if (args.Value == "Spanish")
        {
            var locale = await Http.GetJsonAsync<object>("es.json");
            var sup1 = await Http.GetJsonAsync<object>("numberingSystems.json");
            var sup2 = await Http.GetJsonAsync<object>("ca-gregorian.json");
            var sup3 = await Http.GetJsonAsync<object>("numbers.json");
            var sup4 = await Http.GetJsonAsync<object>("timeZoneNames.json");
            var sup5 = await Http.GetJsonAsync<object>("currencies.json");

        var cldrData = new object[] { sup1, sup2, sup3, sup4 ,sup5};

            this.JsRuntime.Ejs().LoadLocaleData(locale).SetCulture("es").LoadCldrData(cldrData);



        }
        else if (args.Value == "German")
        {
            var locale1 = await Http.GetJsonAsync<object>("de.json");
            var sup11 = await Http.GetJsonAsync<object>("de/numberingSystems.json");
            var sup12 = await Http.GetJsonAsync<object>("de/ca-gregorian.json");
            var sup13 = await Http.GetJsonAsync<object>("de/numbers.json");
            var sup14 = await Http.GetJsonAsync<object>("de/timeZoneNames.json");
            var sup15 = await Http.GetJsonAsync<object>("de/currencies.json");

        var cldrData1 = new object[] { sup11, sup12, sup13, sup14 ,sup15};

            this.JsRuntime.Ejs().LoadLocaleData(locale1).SetCulture("de").LoadCldrData(cldrData1);
        }
        StateHasChanged();
    }

`
**Sample Link:** https://www.syncfusion.com/downloads/support/directtrac/general/ze/BlazorApp-locale1301336185

Please let us know if you have any concerns.

Regards,
Saranya M
