### ISSUE TITLE
DropDownListTemplates inside Grid throw an error

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#77]
```
<GridColumns>
        <GridColumn Field=@nameof(Company.Id) HeaderText="Company identifier" IsPrimaryKey="true" TextAlign="TextAlign.Right" Width="120" Visible="false"></GridColumn>

        <GridColumn Field="LegalPersonTypeId" HeaderText="Legal Person Type" Width="100">
            <Template>
                @{
                    var company = (context as Company);
                    <span>@company.LegalPersonType.Name</span>
                }
            </Template>
            <EditTemplate>
                <EjsDropDownList TValue="string" ID="LegalPersonTypeId" Value="@((context as Company).LegalPersonTypeId)" Placeholder="Select a game" DataSource="@legalPersonTypes">
                    <DropDownListTemplates>
                        <ItemTemplate Context="anotherContext">
                            <span>@((anotherContext as LegalPersonType).Name)</span>
                        </ItemTemplate>
                    </DropDownListTemplates>
                    <DropDownListFieldSettings Value="Id" Text="Name"></DropDownListFieldSettings>
                </EjsDropDownList>
            </EditTemplate>
        </GridColumn>
    </GridColumns>
```

Where LegalPersonType is:

```
public class LegalPersonType
    {
        public string Id { get; set; }

        public string Name { get; set; }
    }
```

Error:
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/3521524/69502173-bf614c80-0ed1-11ea-8363-61b4e93c8a5d.png">

> Another thing is that the <DropDownListFieldSettings Value="Id" Text="Name"></DropDownListFieldSettings> isn't working because always set the Value of the DDL as the value of the column specified in the Text parameter, in this case "Name"

**Comment by saranya-dhayalan** [comment]
Hi Team,

Thank you for contacting Syncfusion support

We checked your code snippet and reported the issue. The reason for this issue is that you need to set the ModelType in the Dropdownlist component. To use templates, the Dropdownlist must be linked to the named model. This can be done by specifying the type of model using the ModelType property of the Dropdownlist component as follows. Please find the code snippet below:

    <EjsGrid ModelType="@Model" DataSource="@Orders" AllowPaging="true" Height="200" @ref="Grid" Toolbar="@(new List<string>() { "Add", "Edit", "Delete", "Cancel", "Update" })">
        <GridEditSettings AllowAdding="true" AllowEditing="true" AllowDeleting="true" Mode="EditMode.Normal"></GridEditSettings>
        <GridColumns>
            <GridColumn Field=@nameof(Order.OrderID) HeaderText="Order ID" TextAlign="TextAlign.Right" Width="120"></GridColumn>
            <GridColumn Field=@nameof(Order.CustomerID) HeaderText="Customer Name" Width="150">
                <Template>
                    @{
                        <span>@((context as Order).OrderID)</span>
                    }
                </Template>
                <EditTemplate>
                    <EjsDropDownList ModelType="@Model" TValue="string" ID="LegalPersonTypeId" Value="@((context as Order).CustomerID)" Placeholder="Select a Name" DataSource="@Orders">
                        <DropDownListTemplates>
                            <ItemTemplate Context="anotherContext">
                                <span>@((anotherContext as Order).CustomerID)</span>
                            </ItemTemplate>
                        </DropDownListTemplates>
                        <DropDownListFieldSettings Text="CustomerID" Value="CustomerID"></DropDownListFieldSettings>
                    </EjsDropDownList>
                </EditTemplate>
            </GridColumn>
        </GridColumns>
    </EjsGrid>

@code{

        EjsGrid<Order> Grid;
        public List<Order> Orders { get; set; }
        Order Model = new Order();
}


For your convenience, we have prepared a sample. please find the below sample link:

Sample link: https://www.syncfusion.com/downloads/support/directtrac/256212/ze/BlazorApp3-203357710

Could you please check the above sample and get back to us if you need further assistance on this?

Regards,
Saranya D

**Comment by OscarCanek** [comment]
The ModelType of the grid is the same as the ModelType of the DropDownList?

**Comment by OscarCanek** [comment]
Th link show me: Access Denied

**Comment by saranya-dhayalan** [comment]
Hi Oscar,

Yes, the same model used for both Grid and Dropdownlist. Please find the attached sample.
[BlazorApp3-203357710.zip](https://github.com/syncfusion/ej2-blazor-samples/files/3921539/BlazorApp3-203357710.zip)

Regards,
Saranya D

**Comment by ahmetsekmen** [comment]
Can you make same example for Customer Object?
I mean
class Customer{
  int CustomerId=1, 
  string CustomerName=Adam
}

I am trying this almost two days.
