### ISSUE TITLE
Compatibility with wasm 3.1.0-preview4.19579.2 template 

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#80]
I'm using `blazor wasm`, I created the project using the template `Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2` with CLI with the following command `dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2` like the docs [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=netcore-cli) explain.

Also I followed this [Getting started with Syncfusion Blazor - WebAssembly App in .NET Core CLI](https://ej2.syncfusion.com/blazor/documentation/getting-started/dotnet-cli-blazor/), using the template `3.1.0-preview4.19579.2` instead of `3.1.0-preview3.19555.2`

The result is the following:

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/3521524/70576962-d362aa80-1b6f-11ea-8243-5592a246d2f1.png">

I also added this to index.html `<script src="https://cdn.syncfusion.com/ej2/17.2.29/dist/ejs.interop.min.js"></script>`

**Comment by Saranya13** [comment]
HI @OscarCanek ,

We have checked your reported issue and we are able to reproduce the reported issue. We are currently working on providing the latest SDK 3.1.100 support to our blazor components and we will complete and include our Volume 4 main release, which will be available on mid of December 2019.

We would like to let you know that, you should use the same version of Nuget and client resources in your application.

Please let us know if you have any concerns.

Regards,
Saranya M

**Comment by sridurgha** [comment]
Hi @OscarCanek ,

We are glad to announce that our Essential Studio Volume 4, 2019 release (v17.4.0.39) is rolled out and is available for download under the following link.

https://www.syncfusion.com/forums/150001/essential-studio-2019-volume-4-release-v17-4-0-39-is-available-for-download

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Sridurgha U
