### ISSUE TITLE
Diagram context always empty on NodeTemplate 

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#85]
I have a diagram like the following:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3521524/77242206-94f27800-6bc1-11ea-88e9-44d2643b3154.png">

The `Node` class is the following:

```c#
 public class Node
    {
        public string Name { get; set; }
        public string FillColor { get; set; }
        public string Category { get; set; }
    }
```

All the properties of the object are always null.

BTW I’m using the ‘18.1.36-beta’ version.

Could you help me please?

**Comment by gshyam93** [comment]
Hi OscarCanek,

We have created a sample in which we have rendered a layout and the node annotation is render using NodeTemplate. Please refer to a code example and the sample below.

Code example:
   <DiagramTemplates>
                <NodeTemplate>
                    @{
                        <div>
                            <span>
                                @((context as Node).data.Name)
                            </span> 
                        </div> 
                    } 
                </NodeTemplate> 
            </DiagramTemplates>  

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/DiagramLayout-1325480134

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
Solution provided and so closing this issue, no update for a long time.
