### ISSUE TITLE
Update annotation at runtime

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#86]
I was trying to update the annotation at runtime but I couldn't make it work. I'm using the `18.1.36-beta` version.

The example from the documentation is the following:

https://blazor.syncfusion.com/documentation/diagram/labels/#update-annotation-at-runtime

I call a method with a button that executes the ` diagram.Nodes[0].Annotations[0].Content = "Updated Annotation";` but the annotation doesn't change.

Could you help me?

**Comment by gshyam93** [comment]
Hi OscarCanek,

We have created a sample in which we have updated the node annotations at runtime. Please refer to a code example and the sample below.


<SfButton @onclick="onToggleClick" CssClass="e-flat" IsToggle="true" IsPrimary="true" Content="@Content"></SfButton>          private void   onToggleClick(Microsoft.AspNetCore.Components.Web.MouseEventArgs args)       {             diagram.Nodes[0].Annotations[0].Content = "Updated Annotation";       }
--


Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/DiagramAnnotationSample1933154459

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
Solution provided and so closing this issue, no update for a long time.
