### ISSUE TITLE
Diagram Refresh method clones the diagram

### ISSUE THREAD

**Issue by OscarCanek** [syncfusion/blazor-samples#87]
Using the `18.1.36-beta` version when I call `diagram.Refresh();` the diagram is cloned, the following image has and example of the result:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/3521524/77243633-e6a2fe80-6bd1-11ea-93b9-31a0a67b21bf.png">

**Comment by gshyam93** [comment]
Hi OscarCanek,

Could you please share us more details such why you are using diagram refresh method in the diagram and also share us an exact requirement in the layout, so that, we can validate and provide a solution.

Regards,
Shyam G

**Comment by Sridhar-Narasimhan** [comment]
We have requested more details and no update for a long time and so closing this issue
